[package]
name = "rust-practice"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
oidn = "1.4.3"
image = "0.24.5"
rand = "0.8.3"
pyo3 = { version = "0.17.2", features = ["extension-module"] }